(function(){"use strict";
var dims=window.SEFS_DIMS;var RK=window.ResultKit;if(RK)RK.configure({id:"sefs",title:"SEFS 主观体验功能状态量表",start:["#startBtn"]});
var labels=["完全不符合","偶尔符合","有时符合","经常符合","几乎总是符合"];
var KEY="sefs-v1-session",HKEY="sefs-v1-history",MAX=30;var ans=Array(24).fill(null),idx=0,agreed=false,timer=0,view="cover",shown=null,curId=null,saveState="none",histFrom="cover",confirmCb=null;
function el(id){return document.getElementById(id)}
function store(){try{sessionStorage.setItem(KEY,JSON.stringify({answers:ans,index:idx,agreed:agreed,view:shown?"history":view,curId:curId}))}catch(e){}}
function load(){try{var s=JSON.parse(sessionStorage.getItem(KEY)||"null");if(!s||!Array.isArray(s.answers)||s.answers.length!==24)return;ans=s.answers.map(function(v){return Number.isInteger(v)&&v>=0&&v<=4?v:null});idx=Number.isInteger(s.index)?Math.max(0,Math.min(23,s.index)):0;agreed=s.agreed===true;curId=typeof s.curId==="string"&&/^[\w-]{1,40}$/.test(s.curId)?s.curId:null;view=s.view==="history"?"history":s.view==="result"&&ans.every(function(v){return v!==null})?"result":s.view==="quiz"?"quiz":"cover"}catch(e){}}
function show(which){["cover","quiz","result","history"].forEach(function(n){el(n).classList.toggle("hidden",n!==which)});view=which;if(which==="cover")refreshCover();store();window.scrollTo(0,0)}
function filled(){return ans.filter(function(x){return x!==null}).length}
function renderQuiz(focus){clearTimeout(timer);show("quiz");if(RK)RK.guard(true,function(){clearTimeout(timer);show("cover")});var d=Math.floor(idx/6);el("dimensionPill").textContent=String(d+1).padStart(2,"0")+" / "+dims[d].title;el("questionCount").textContent=String(idx+1).padStart(2,"0")+" / 24";el("progressFill").style.width=(filled()/24*100)+"%";el("progressTrack").setAttribute("aria-valuenow",filled());el("sectionDots").innerHTML=dims.map(function(_,i){return "<span class=\"section-dot "+(i<d?"done":i===d?"active":"")+"\"></span>"}).join("");el("questionNo").textContent="QUESTION "+String(idx+1).padStart(2,"0");el("questionText").textContent=dims[d].items[idx%6];el("options").innerHTML=labels.map(function(label,value){return "<button type=\"button\" class=\"option "+(ans[idx]===value?"selected":"")+"\" data-score=\""+value+"\" aria-pressed=\""+(ans[idx]===value)+"\"><span class=\"option-value\">"+value+"</span><span class=\"option-label\">"+label+"</span>"+(ans[idx]===value?"<span class=\"option-check\" aria-hidden=\"true\">✓</span>":"")+"</button>"}).join("");el("backBtn").disabled=idx===0;el("nextBtn").disabled=ans[idx]===null;el("nextBtn").textContent=idx===23?"查看结果 →":"下一题 →";if(focus)el("questionText").focus({preventScroll:true})}
function choose(v){clearTimeout(timer);ans[idx]=v;curId=null;store();renderQuiz(false);timer=setTimeout(function(){advance()},390)}
function advance(){clearTimeout(timer);if(ans[idx]===null)return;if(idx<23){idx++;renderQuiz(true)}else{var missing=ans.findIndex(function(x){return x===null});if(missing>=0){idx=missing;renderQuiz(true)}else finish()}}
function level(score){return score<=7?"功能基本完好":score<=11?"轻度受损":score<=18?"中度受损":"重度受损"}
function stats(){return calc(shown?shown.answers:ans)}
function calc(a){var scores=dims.map(function(_,i){return a.slice(i*6,i*6+6).reduce(function(sum,x){return sum+x},0)});var max=Math.max.apply(null,scores);return{scores:scores,total:scores.reduce(function(a,b){return a+b},0),leaders:scores.map(function(s,i){return s===max?i:-1}).filter(function(i){return i>=0}),complex:scores.filter(function(s){return s>=15}).length>=2}}
function radar(scores){var out="",cx=200,cy=163,r=110;function pt(i,v){var angle=-Math.PI/2+i*Math.PI/2;return[cx+Math.cos(angle)*r*v/24,cy+Math.sin(angle)*r*v/24]}function poly(v){return [0,1,2,3].map(function(i){return pt(i,v)[0]+","+pt(i,v)[1]}).join(" ")};[6,12,18,24].forEach(function(n){out+="<polygon points=\""+poly(n)+"\" fill=\"none\" stroke=\"#e2ebe4\" stroke-width=\"1\"/>"});[0,1,2,3].forEach(function(i){var xy=pt(i,24);out+="<line x1=\""+cx+"\" y1=\""+cy+"\" x2=\""+xy[0]+"\" y2=\""+xy[1]+"\" stroke=\"#dce9df\"/>"});out+="<polygon points=\""+scores.map(function(s,i){return pt(i,s).join(",")}).join(" ")+"\" fill=\"#8bb8a0\" fill-opacity=\".38\" stroke=\"#447b5f\" stroke-width=\"2.5\"/>";scores.forEach(function(s,i){var xy=pt(i,s);out+="<circle cx=\""+xy[0]+"\" cy=\""+xy[1]+"\" r=\"5\" fill=\"#417960\" stroke=\"white\" stroke-width=\"2\"/>"});[{x:200,y:23,a:"middle"},{x:365,y:166,a:"middle"},{x:200,y:323,a:"middle"},{x:35,y:166,a:"middle"}].forEach(function(o,i){out+="<text x=\""+o.x+"\" y=\""+o.y+"\" text-anchor=\""+o.a+"\" font-size=\"14\" font-weight=\"650\" fill=\"#456452\">"+dims[i].title+"</text><text x=\""+o.x+"\" y=\""+(o.y+17)+"\" text-anchor=\""+o.a+"\" font-size=\"11\" fill=\"#869c8a\">"+scores[i]+" / 24</text>"});el("radar").innerHTML=out}
function renderResult(rec){shown=rec||null;if(!shown&&ans.some(function(x){return x===null})){idx=ans.findIndex(function(x){return x===null});renderQuiz(true);return}show("result");var s=stats();el("totalScore").textContent=s.total;el("totalCopy").textContent="总分 "+s.total+" 分。它是四个体验维度的简单相加，不设未经验证的总体严重程度阈值。";radar(s.scores);el("dimensionResults").innerHTML=s.scores.map(function(score,i){var d=dims[i];return "<article class=\"dim-card\"><div class=\"dim-head\"><div class=\"dim-title\">"+d.title+"</div><div class=\"dim-score\">"+score+" <small>/ 24</small></div></div><div class=\"mini-track\"><div class=\"mini-fill\" style=\"width:"+(score/24*100)+"%;--tone:"+d.color+"\"></div></div><div class=\"dim-meta\"><span>"+d.brief+"</span><span>"+level(score)+"*</span></div></article>"}).join("");var names=s.leaders.map(function(i){return dims[i].title+"（"+dims[i].type+"）"});var lead=s.leaders.length>1?"并列最高的体验方向："+names.join("、"):"相对突出的体验方向："+names[0];var ordered=s.scores.map(function(score,i){return{score:score,i:i}}).sort(function(a,b){return b.score-a.score||a.i-b.i});var advice=s.leaders.length===1?dims[s.leaders[0]].suggest:"本次有多个并列维度。可以先选一个自己最想了解、最不让你感到负担的方向，慢慢观察。";var comp=s.complex?"按草案规则，有至少两个维度达到 15 分，属于“复合关注”模式。得分排序只是本次观察顺序，不等于临床干预优先级。":"按草案规则，本次未达到“两个及以上维度均不少于 15 分”的复合关注条件。";el("insight").innerHTML="<span class=\"tag\">探索性分析 · 非病理诊断</span><h3>"+lead+"</h3><p>"+comp+"</p><p><strong>可以尝试：</strong>"+advice+"</p><p style=\"color:#829086;font-size:12px\">四维度从高到低："+ordered.map(function(x){return dims[x.i].title+" "+x.score+"分"}).join(" · ")+"。* 维度分段沿用所提供草案，尚未建立临床解释效度。</p>";resultChrome()}
function closeModal(id){el(id).classList.add("hidden");document.body.classList.remove("no-scroll")}
function openModal(id){el(id).classList.remove("hidden");document.body.classList.add("no-scroll")}
function reset(){clearTimeout(timer);if(RK)RK.nickReset();try{sessionStorage.removeItem(KEY)}catch(e){}ans=Array(24).fill(null);idx=0;agreed=false;curId=null;shown=null;el("agree").checked=false;el("agreeHint").hidden=true;closeModal("privacyModal");closeModal("shareModal");show("cover")}
function reportTime(){if(shown)return shown.t;if(curId){var r=readHistory().items.filter(function(x){return x.id===curId})[0];if(r)return r.t}return Date.now()}
function nickOf(){var n="";if(shown)n=shown.nick||"";else{if(curId){var r=readHistory().items.filter(function(x){return x.id===curId})[0];if(r)n=r.nick||""}if(!n&&!curId&&RK)n=RK.nick.get()}return n}
function wrapText(g,t,maxW){var out=[],line="";for(var i=0;i<t.length;i++){var ch=t.charAt(i);if(ch==="\n"){out.push(line);line="";continue}if(line&&g.measureText(line+ch).width>maxW){out.push(line);line=ch}else line+=ch}if(line||!out.length)out.push(line);return out}
/* 报告图：按结果页的全部板块逐块排版（高度随内容自适应），再按画布上限自动选择清晰度，顶部带「昵称 的测评结果」和日期 */
function report(){var s=stats(),nk=nickOf()||"匿名",when=reportTime(),W=1080,X=110,CW=860,FONT="-apple-system, BlinkMacSystemFont, PingFang SC, Microsoft YaHei, sans-serif";
var sc=document.createElement("canvas").getContext("2d"),ops=[],y=0;
function fnt(size,weight){return (weight||"500")+" "+size+"px "+FONT}
function rr(x,yy,w,h,r,color,stroke){ops.push(function(g){g.beginPath();if(g.roundRect)g.roundRect(x,yy,w,h,r);else g.rect(x,yy,w,h);if(stroke){g.strokeStyle=stroke;g.lineWidth=2;g.stroke()}if(color){g.fillStyle=color;g.fill()}})}
function T(t,x,yy,size,color,weight,align){ops.push(function(g){g.fillStyle=color;g.textAlign=align||"left";g.font=fnt(size,weight);g.fillText(t,x,yy)})}
function P(t,size,color,weight,lh,x,w){x=x==null?X:x;w=w||CW;sc.font=fnt(size,weight);var lines=wrapText(sc,t,w);lines.forEach(function(l,i){T(l,x,y+i*lh+Math.round((lh-size)/2+size*0.82),size,color,weight)});y+=lines.length*lh}
y=0;
var head=[];
T("SEFS   /   SUBJECTIVE EXPERIENCE",X,140,24,"#71917c","700");T("YOUR EXPERIENCE MAP",X,176,20,"#9bb0a0","700");
T("你的主观体验地图",X,258,63,"#294c3a","650");y=268;
P("这些数字只是一次观察，不能定义完整的你。",29,"#758c7a","500",42);
y+=6;P("一次自我观察，而不是对你的定义。",26,"#8a9d8e","500",38);
y+=14;var nb=y;rr(X,nb,CW,0,0);var nbIdx=ops.length-1;
y+=44;P(nk+" 的测评结果",40,"#294c3a","700",56,X+28,CW-56);P(fmtTime(when),26,"#6a8773","500",38,X+28,CW-56);y+=24;
(function(h){ops[nbIdx]=function(g){g.beginPath();if(g.roundRect)g.roundRect(X,nb,CW,h,24);else g.rect(X,nb,CW,h);g.fillStyle="#e4eee6";g.fill()}})(y-nb);
y+=34;var sy=y;rr(X,sy,CW,236,28,"#edf5ec");T(String(s.total),X+35,sy+155,124,"#2e6147","700");T("/ 96",X+245,sy+146,38,"#829987","500");T("四个维度总计 · 不对应临床诊断阈值",X+35,sy+201,24,"#63836b","500");y=sy+236+26;
P("总分 "+s.total+" 分。它是四个体验维度的简单相加，不设未经验证的总体严重程度阈值。",26,"#5c7466","500",40);
y+=34;T("四个维度，四种体验",X,y+34,38,"#294b39","700");y+=64;
var RS=2.1,rw=400*RS,rh=360*RS,rx=(W-rw)/2,ry=y;
ops.push(function(g){g.save();g.translate(rx,ry);g.scale(RS,RS);var cx=200,cy=163,r=110;function pt(i,v){var a=-Math.PI/2+i*Math.PI/2;return[cx+Math.cos(a)*r*v/24,cy+Math.sin(a)*r*v/24]}
[6,12,18,24].forEach(function(n){g.beginPath();[0,1,2,3].forEach(function(i){var p=pt(i,n);i?g.lineTo(p[0],p[1]):g.moveTo(p[0],p[1])});g.closePath();g.strokeStyle="#e2ebe4";g.lineWidth=1;g.stroke()});
[0,1,2,3].forEach(function(i){var p=pt(i,24);g.beginPath();g.moveTo(cx,cy);g.lineTo(p[0],p[1]);g.strokeStyle="#dce9df";g.lineWidth=1;g.stroke()});
g.beginPath();s.scores.forEach(function(v,i){var p=pt(i,v);i?g.lineTo(p[0],p[1]):g.moveTo(p[0],p[1])});g.closePath();g.fillStyle="rgba(139,184,160,.38)";g.fill();g.strokeStyle="#447b5f";g.lineWidth=2.5;g.stroke();
s.scores.forEach(function(v,i){var p=pt(i,v);g.beginPath();g.arc(p[0],p[1],5,0,Math.PI*2);g.fillStyle="#417960";g.fill();g.strokeStyle="#fff";g.lineWidth=2;g.stroke()});
g.textAlign="center";[{x:200,y:23},{x:365,y:166},{x:200,y:323},{x:35,y:166}].forEach(function(o,i){g.font=fnt(14,"650");g.fillStyle="#456452";g.fillText(dims[i].title,o.x,o.y);g.font=fnt(11,"500");g.fillStyle="#869c8a";g.fillText(s.scores[i]+" / 24",o.x,o.y+17)});g.restore()});
y+=rh+10;
s.scores.forEach(function(score,i){var d=dims[i],by=y;rr(X,by,CW,138,22,"#f6faf5","#e3ece5");T(d.title,X+28,by+46,31,"#355342","600");T(score+" / 24",X+CW-28,by+46,30,"#355342","600","right");rr(X+28,by+62,CW-56,18,9,"#e9efea");if(score>0)rr(X+28,by+62,Math.max(16,score/24*(CW-56)),18,9,d.color);T(d.brief,X+28,by+112,23,"#829285");T(level(score)+"*",X+CW-28,by+112,23,"#829285","500","right");y+=138+16});
y+=14;var names=s.leaders.map(function(i){return dims[i].title+"（"+dims[i].type+"）"});var lead=s.leaders.length>1?"并列最高的体验方向："+names.join("、"):"相对突出的体验方向："+names[0];
var ordered=s.scores.map(function(v,i){return{score:v,i:i}}).sort(function(a,b){return b.score-a.score||a.i-b.i});var advice=s.leaders.length===1?dims[s.leaders[0]].suggest:"本次有多个并列维度。可以先选一个自己最想了解、最不让你感到负担的方向，慢慢观察。";
var comp=s.complex?"按草案规则，有至少两个维度达到 15 分，属于“复合关注”模式。得分排序只是本次观察顺序，不等于临床干预优先级。":"按草案规则，本次未达到“两个及以上维度均不少于 15 分”的复合关注条件。";
var ib=y,iIdx;rr(X,ib,CW,0,0);iIdx=ops.length-1;y+=34;T("探索性分析 · 非病理诊断",X+28,y+22,22,"#4f7c63","700");y+=44;
P(lead,32,"#294b39","700",46,X+28,CW-56);y+=8;P(comp,26,"#4a6455","500",40,X+28,CW-56);y+=8;P("可以尝试："+advice,26,"#4a6455","500",40,X+28,CW-56);y+=8;
P("四维度从高到低："+ordered.map(function(x){return dims[x.i].title+" "+x.score+"分"}).join(" · ")+"。* 维度分段沿用所提供草案，尚未建立临床解释效度。",22,"#829086","500",34,X+28,CW-56);y+=28;
(function(h){ops[iIdx]=function(g){g.beginPath();if(g.roundRect)g.roundRect(X,ib,CW,h,24);else g.rect(X,ib,CW,h);g.fillStyle="#f1f6f1";g.fill()}})(y-ib);
y+=28;var nt=el("shareModal")&&document.querySelector(".notice")?document.querySelector(".notice").textContent.trim():"";var nb2=y;rr(X,nb2,CW,0,0);var n2=ops.length-1;y+=30;
P(nt,22,"#6b6254","500",34,X+24,CW-48);y+=26;(function(h){ops[n2]=function(g){g.beginPath();if(g.roundRect)g.roundRect(X,nb2,CW,h,18);else g.rect(X,nb2,CW,h);g.fillStyle="#f7f1e3";g.fill()}})(y-nb2);
y+=40;P("本报告为探索性自评；量表阈值及类型尚未经验证。",22,"#859488","500",36);P("仅供个人参考，不可用于诊断或决定治疗。",22,"#859488","500",36);
var H=y+84;
var scale=Math.max(0.6,Math.min(2,Math.sqrt(15000000/(W*H))));
function make(k){var c=document.createElement("canvas");c.width=Math.round(W*k);c.height=Math.round(H*k);var g=c.getContext("2d");g.scale(k,k);g.fillStyle="#f5f8f3";g.fillRect(0,0,W,H);var grad=g.createLinearGradient(0,0,W,Math.min(H,700));grad.addColorStop(0,"#e1eee2");grad.addColorStop(1,"#faf1e8");g.fillStyle=grad;g.fillRect(0,0,W,Math.min(H,640));g.beginPath();if(g.roundRect)g.roundRect(54,58,972,H-116,38);else g.rect(54,58,972,H-116);g.fillStyle="#fff";g.fill();g.textBaseline="alphabetic";ops.forEach(function(op){op(g)});return c.toDataURL("image/png")}
var url="";try{url=make(scale)}catch(e){url=""}if(!url||url.length<2000){try{url=make(1)}catch(e){url=""}}
if(!url||url.length<2000){alert("这台设备没能生成图片，可以直接截屏保存。");return}
el("reportImage").src=url;el("downloadLink").href=url;el("downloadLink").setAttribute("download","SEFS-"+(nk!=="匿名"?nk+"-":"")+"体验地图.png");openModal("shareModal")}
/* ===== 历史结果（localStorage）===== */
function done(){return filled()===24&&!!curId}
function lsOk(){try{var k="sefs-v1-probe";window.localStorage.setItem(k,"1");window.localStorage.removeItem(k);return true}catch(e){return false}}
function validRec(r){return r&&typeof r==="object"&&typeof r.t==="number"&&isFinite(r.t)&&Array.isArray(r.answers)&&r.answers.length===24&&r.answers.every(function(v){return Number.isInteger(v)&&v>=0&&v<=4})}
function readHistory(){var raw,bad={items:[],status:"corrupt",dropped:0};try{raw=window.localStorage.getItem(HKEY)}catch(e){return{items:[],status:"unavailable",dropped:0}}
if(raw===null||raw===undefined)return{items:[],status:"ok",dropped:0};var d;try{d=JSON.parse(raw)}catch(e){bad.raw=raw;return bad}
var arr=Array.isArray(d)?d:d&&Array.isArray(d.items)?d.items:null;if(!arr){bad.raw=raw;return bad}
var out=[],seen={};arr.forEach(function(r){if(!validRec(r))return;var id=String(r.id||"").replace(/[^\w-]/g,"").slice(0,40);if(!id||seen[id])id="r"+Math.round(r.t).toString(36)+Math.random().toString(36).slice(2,6);seen[id]=1;out.push({id:id,t:r.t,answers:r.answers.slice(),nick:typeof r.nick==="string"?(RK?RK.nick.clean(r.nick):r.nick.replace(/[<>&"'`\\\x00-\x1f]/g,"").slice(0,12)):""})});
out.sort(function(x,y){return y.t-x.t});return{items:out.slice(0,MAX),status:"ok",dropped:arr.length-out.length}}
function writeHistory(items){try{var list=items.map(function(r){var c=calc(r.answers);return{id:r.id,t:r.t,nick:r.nick||"",answers:r.answers,scores:c.scores,total:c.total,leaders:c.leaders,complex:c.complex}});window.localStorage.setItem(HKEY,JSON.stringify({v:1,max:MAX,items:list}));return true}catch(e){return false}}
function addHistory(rec){var h=readHistory();if(h.status==="unavailable")return{ok:false,state:"unavail"};var recovered=false;if(h.status==="corrupt"){recovered=true;try{window.localStorage.setItem(HKEY+"-corrupt-backup",h.raw)}catch(e){}}
var ok=writeHistory([rec].concat(h.items).slice(0,MAX));return{ok:ok,state:ok?(recovered?"recovered":"ok"):"fail"}}
function finish(){var t=Date.now(),rec={id:"r"+t.toString(36)+Math.random().toString(36).slice(2,6),t:t,answers:ans.slice(),nick:RK?RK.nick.get():""};var r=addHistory(rec);curId=r.ok?rec.id:null;saveState=r.state;renderResult()}
function pad(n){return String(n).padStart(2,"0")}
function fmtTime(t){var d=new Date(t);return d.getFullYear()+"-"+pad(d.getMonth()+1)+"-"+pad(d.getDate())+" "+pad(d.getHours())+":"+pad(d.getMinutes())}
function leadText(c){return c.leaders.map(function(i){return dims[i].title}).join("、")}
function resultChrome(){var h=!!shown,b=el("histBanner"),n=el("saveNote");b.hidden=!h;n.hidden=h;if(h)b.textContent="历史记录 · "+(shown.nick?shown.nick+" · ":"")+fmtTime(shown.t)+" · 只读查看";
else{var msg={ok:"✓ 本次结果已自动保存到本机历史（仅存于此浏览器，不会上传）。",recovered:"✓ 本次结果已保存。原来的历史数据已损坏无法读取，已重新开始记录。",unavail:"⚠ 当前浏览器无法使用本地存储（可能被禁用或处于无痕模式），本次结果没有保存。可以先点“生成报告图片”留存。",fail:"⚠ 保存失败（存储空间不足或被浏览器限制），本次结果没有保存到历史。可以先点“生成报告图片”留存。"}[saveState];n.textContent=msg||"";n.hidden=!msg;n.className="save-note"+(saveState==="ok"||saveState==="recovered"?"":" warn")}
el("resultHistBtn").textContent=h?"← 返回历史列表":"我的历史结果 →"}
function refreshCover(){var f=filled(),d=done(),h=readHistory(),w=el("storageWarn"),prog=f>0&&!d;el("resumeNote").hidden=!prog;el("startBtn").innerHTML=(prog?"继续上次探索":"开始探索")+" <span aria-hidden=\"true\">↗</span>";el("homeRestartBtn").hidden=!(f>0||h.items.length>0);el("homeHistCount").textContent=h.items.length;
w.hidden=h.status==="ok";w.textContent=h.status==="unavailable"?"⚠ 当前浏览器禁用了本地存储，测评结果将无法保存到历史，其余功能不受影响。":h.status==="corrupt"?"⚠ 本机历史数据已损坏，暂时无法读取。可以在“我的历史结果”中重置；再次完成测评也会自动重新开始记录。":""}
function restartQuiz(){clearTimeout(timer);if(RK)RK.nickReset();ans=Array(24).fill(null);idx=0;curId=null;shown=null;saveState="none";agreed=true;el("agree").checked=true;el("agreeHint").hidden=true;closeModal("privacyModal");closeModal("shareModal");renderQuiz(true)}
function requestRestart(){if(filled()>0&&!curId&&!shown)askConfirm("重新测一遍？","当前作答还没有保存到历史，重新开始会丢弃它。已保存的历史结果不受影响。","重新开始",restartQuiz);else restartQuiz()}
function openHistory(from){histFrom=from||"cover";shown=null;show("history");renderHistory();el("historyTitle").focus({preventScroll:true})}
function leaveHistory(){if(histFrom==="result"&&filled()===24){if(saveState==="none")saveState=curId?"ok":"fail";renderResult()}else show("cover")}
function esc(t){return String(t).replace(/[&<>"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]})}
function renderHistory(){var h=readHistory(),al=el("histAlert"),msgs=[];
if(h.status==="unavailable")msgs.push("当前浏览器禁用了本地存储，无法读取或保存历史结果。")
else if(h.status==="corrupt")msgs.push("本机历史数据已损坏，无法读取。你可以重置历史数据后重新开始记录。<br><button class=\"secondary\" type=\"button\" id=\"histResetBtn\" style=\"margin-top:10px\">重置历史数据</button>");
if(h.dropped>0)msgs.push("有 "+h.dropped+" 条损坏的记录已被忽略。");
al.hidden=!msgs.length;al.innerHTML=msgs.join("<br>");
var list=h.items,L=el("histList");el("histClearBtn").hidden=!list.length;
if(!list.length){L.innerHTML=h.status==="ok"?"<div class=\"hist-empty\"><div class=\"hist-empty-mark\" aria-hidden=\"true\">✳</div><p>还没有历史结果。<br>完成一次测评后，结果会自动保存在这里。</p></div>":"";el("histCompare").innerHTML="";return}
L.innerHTML=list.map(function(r,n){var c=calc(r.answers);return "<article class=\"hist-item\"><button type=\"button\" class=\"hist-open\" data-open=\""+r.id+"\" aria-label=\"查看 "+fmtTime(r.t)+" 的结果，总分 "+c.total+"\"><span class=\"hist-top\"><span class=\"hist-time\">"+fmtTime(r.t)+(r.nick?" · "+esc(r.nick):"")+"</span>"+(n===0?"<span class=\"hist-tag\">最新</span>":"")+"</span><span class=\"hist-main\"><b>"+c.total+"</b><small> / 96</small><span class=\"hist-sum\">突出：<em>"+leadText(c)+"</em>"+(c.complex?" · 复合关注":"")+"</span></span><span class=\"hist-mini\" aria-hidden=\"true\">"+c.scores.map(function(s,i){return "<span class=\"hist-bar\"><i style=\"width:"+(s/24*100)+"%;background:"+dims[i].color+"\"></i><u>"+s+"</u></span>"}).join("")+"</span></button><button type=\"button\" class=\"hist-del\" data-del=\""+r.id+"\" aria-label=\"删除 "+fmtTime(r.t)+" 的记录\">删除</button></article>"}).join("");
if(list.length>=2){var a=calc(list[0].answers),b=calc(list[1].answers);function dl(x,y){var d=x-y;return d>0?"+"+d:d<0?"−"+(-d):"持平"}
el("histCompare").innerHTML="<div class=\"compare\"><h2 class=\"h2\" style=\"margin-top:0\">最近两次对比</h2><p class=\"fine\" style=\"margin:0 0 10px\">上一次 "+fmtTime(list[1].t)+" → 最近一次 "+fmtTime(list[0].t)+"</p><div class=\"cmp-table\" role=\"table\" aria-label=\"最近两次分数对比\">"+dims.map(function(d,i){return "<div class=\"cmp-row\" role=\"row\"><span class=\"cmp-name\">"+d.title+"</span><span class=\"cmp-val\">"+b.scores[i]+" → "+a.scores[i]+"</span><span class=\"cmp-delta\">"+dl(a.scores[i],b.scores[i])+"</span></div>"}).join("")+"<div class=\"cmp-row cmp-total\" role=\"row\"><span class=\"cmp-name\">总分</span><span class=\"cmp-val\">"+b.total+" → "+a.total+"</span><span class=\"cmp-delta\">"+dl(a.total,b.total)+"</span></div></div><p class=\"fine\" style=\"margin:10px 0 0\">变化只反映两次自评之间的差异，不代表好转或恶化。</p></div>"}else el("histCompare").innerHTML=""}
function askConfirm(title,text,yes,cb){confirmCb=cb;el("confirmTitle").textContent=title;el("confirmText").textContent=text;el("confirmYes").textContent=yes||"确定";openModal("confirmModal");el("confirmNo").focus()}
function cancelConfirm(){if(el("confirmModal").classList.contains("hidden"))return;confirmCb=null;closeModal("confirmModal")}
function dropCurrent(id){if(curId&&(!id||curId===id)){clearTimeout(timer);ans=Array(24).fill(null);idx=0;curId=null;saveState="none";histFrom="cover";store()}}
function afterHistoryChange(){if(!el("history").classList.contains("hidden"))renderHistory();else refreshCover()}
function clearAllHistory(){var n=readHistory().items.length;askConfirm("清空全部历史结果？","将删除本机保存的全部 "+n+" 条历史结果，且无法恢复。",  "全部清空",function(){try{window.localStorage.removeItem(HKEY)}catch(e){}dropCurrent();afterHistoryChange()})}
el("confirmYes").addEventListener("click",function(){var cb=confirmCb;confirmCb=null;closeModal("confirmModal");if(cb)cb()});el("confirmNo").addEventListener("click",cancelConfirm);el("confirmModal").addEventListener("click",function(e){if(e.target===el("confirmModal"))cancelConfirm()});
el("historyBtn").addEventListener("click",function(){clearTimeout(timer);openHistory(view==="history"||shown?histFrom:view==="result"?"result":"cover")});
el("homeHistBtn").addEventListener("click",function(){openHistory("cover")});
el("resultHistBtn").addEventListener("click",function(){if(shown)openHistory(histFrom);else openHistory("result")});
el("homeRestartBtn").addEventListener("click",function(){if(!el("agree").checked){el("agreeHint").hidden=false;el("agree").focus();return}requestRestart()});
el("histNewBtn").addEventListener("click",requestRestart);
el("histBackBtn").addEventListener("click",leaveHistory);
el("histClearBtn").addEventListener("click",clearAllHistory);el("clearHistBtn").addEventListener("click",function(){var n=readHistory().items.length;if(!n){askConfirm("没有可清空的历史","本机目前没有保存的历史结果。","知道了",function(){});return}clearAllHistory()});
el("histAlert").addEventListener("click",function(e){if(e.target.id==="histResetBtn")askConfirm("重置历史数据？","将删除本机无法读取的历史数据并重新开始记录。","重置",function(){try{window.localStorage.removeItem(HKEY)}catch(x){}renderHistory()})});
el("histList").addEventListener("click",function(e){var o=e.target.closest("[data-open]"),d=e.target.closest("[data-del]");
if(o){var r=readHistory().items.filter(function(x){return x.id===o.getAttribute("data-open")})[0];if(r)renderResult(r);else renderHistory();return}
if(d){var id=d.getAttribute("data-del"),r2=readHistory().items.filter(function(x){return x.id===id})[0];if(!r2){renderHistory();return}var c=calc(r2.answers);
askConfirm("删除这条记录？",fmtTime(r2.t)+" · 总分 "+c.total+" / 96。删除后无法恢复。","删除",function(){var hh=readHistory();if(hh.status!=="ok")return renderHistory();writeHistory(hh.items.filter(function(x){return x.id!==id}));dropCurrent(id);renderHistory()})}});
el("agree").addEventListener("change",function(e){agreed=e.target.checked;if(agreed)el("agreeHint").hidden=true;store()});el("startBtn").addEventListener("click",function(){if(!el("agree").checked){el("agreeHint").hidden=false;el("agree").focus();return}agreed=true;var go=function(){if(done())restartQuiz();else renderQuiz(true)};if(RK)RK.ensureNick(go);else go()});el("options").addEventListener("click",function(e){var b=e.target.closest("button[data-score]");if(b)choose(Number(b.getAttribute("data-score")))});el("backBtn").addEventListener("click",function(){clearTimeout(timer);if(idx>0){idx--;renderQuiz(true)}});el("nextBtn").addEventListener("click",advance);el("exitBtn").addEventListener("click",function(){clearTimeout(timer);show("cover")});el("privacyBtn").addEventListener("click",function(){openModal("privacyModal")});el("shareBtn").addEventListener("click",report);el("restartBtn").addEventListener("click",function(){requestRestart()});el("clearBtn").addEventListener("click",function(){askConfirm("清除本次答题进度？","只清除当前未保存的作答，已保存的历史结果不受影响。","清除",function(){reset()})});document.querySelectorAll("[data-close]").forEach(function(b){b.addEventListener("click",function(){closeModal(b.getAttribute("data-close"))})});["privacyModal","shareModal"].forEach(function(id){el(id).addEventListener("click",function(e){if(e.target===el(id))closeModal(id)})});document.addEventListener("keydown",function(e){if(e.key==="Escape"){closeModal("privacyModal");closeModal("shareModal");cancelConfirm()}});
load();el("agree").checked=agreed;if(view==="quiz")renderQuiz(false);else if(view==="result"){saveState=curId?"ok":lsOk()?"fail":"unavail";renderResult()}else if(view==="history")openHistory("cover");else show("cover");
window.SEFS_APP_READY=true;
})();