(function(){"use strict";
var dims=window.SEFS_DIMS;
var labels=["完全不符合","偶尔符合","有时符合","经常符合","几乎总是符合"];
var KEY="sefs-v1-session";var ans=Array(24).fill(null),idx=0,agreed=false,timer=0,view="cover";
function el(id){return document.getElementById(id)}
function store(){try{sessionStorage.setItem(KEY,JSON.stringify({answers:ans,index:idx,agreed:agreed,view:view}))}catch(e){}}
function load(){try{var s=JSON.parse(sessionStorage.getItem(KEY)||"null");if(!s||!Array.isArray(s.answers)||s.answers.length!==24)return;ans=s.answers.map(function(v){return Number.isInteger(v)&&v>=0&&v<=4?v:null});idx=Number.isInteger(s.index)?Math.max(0,Math.min(23,s.index)):0;agreed=s.agreed===true;view=s.view==="result"&&ans.every(function(v){return v!==null})?"result":s.view==="quiz"?"quiz":"cover"}catch(e){}}
function show(which){["cover","quiz","result"].forEach(function(n){el(n).classList.toggle("hidden",n!==which)});view=which;store();window.scrollTo(0,0)}
function filled(){return ans.filter(function(x){return x!==null}).length}
function renderQuiz(focus){clearTimeout(timer);show("quiz");var d=Math.floor(idx/6);el("dimensionPill").textContent=String(d+1).padStart(2,"0")+" / "+dims[d].title;el("questionCount").textContent=String(idx+1).padStart(2,"0")+" / 24";el("progressFill").style.width=(filled()/24*100)+"%";el("progressTrack").setAttribute("aria-valuenow",filled());el("sectionDots").innerHTML=dims.map(function(_,i){return "<span class=\"section-dot "+(i<d?"done":i===d?"active":"")+"\"></span>"}).join("");el("questionNo").textContent="QUESTION "+String(idx+1).padStart(2,"0");el("questionText").textContent=dims[d].items[idx%6];el("options").innerHTML=labels.map(function(label,value){return "<button type=\"button\" class=\"option "+(ans[idx]===value?"selected":"")+"\" data-score=\""+value+"\" aria-pressed=\""+(ans[idx]===value)+"\"><span class=\"option-value\">"+value+"</span><span class=\"option-label\">"+label+"</span>"+(ans[idx]===value?"<span class=\"option-check\" aria-hidden=\"true\">✓</span>":"")+"</button>"}).join("");el("backBtn").disabled=idx===0;el("nextBtn").disabled=ans[idx]===null;el("nextBtn").textContent=idx===23?"查看结果 →":"下一题 →";if(focus)el("questionText").focus({preventScroll:true})}
function choose(v){clearTimeout(timer);ans[idx]=v;store();renderQuiz(false);timer=setTimeout(function(){advance()},390)}
function advance(){clearTimeout(timer);if(ans[idx]===null)return;if(idx<23){idx++;renderQuiz(true)}else{var missing=ans.findIndex(function(x){return x===null});if(missing>=0){idx=missing;renderQuiz(true)}else renderResult()}}
function level(score){return score<=7?"功能基本完好":score<=11?"轻度受损":score<=18?"中度受损":"重度受损"}
function stats(){var scores=dims.map(function(_,i){return ans.slice(i*6,i*6+6).reduce(function(sum,x){return sum+x},0)});var max=Math.max.apply(null,scores);return{scores:scores,total:scores.reduce(function(a,b){return a+b},0),leaders:scores.map(function(s,i){return s===max?i:-1}).filter(function(i){return i>=0}),complex:scores.filter(function(s){return s>=15}).length>=2}}
function radar(scores){var out="",cx=200,cy=163,r=110;function pt(i,v){var angle=-Math.PI/2+i*Math.PI/2;return[cx+Math.cos(angle)*r*v/24,cy+Math.sin(angle)*r*v/24]}function poly(v){return [0,1,2,3].map(function(i){return pt(i,v)[0]+","+pt(i,v)[1]}).join(" ")};[6,12,18,24].forEach(function(n){out+="<polygon points=\""+poly(n)+"\" fill=\"none\" stroke=\"#e2ebe4\" stroke-width=\"1\"/>"});[0,1,2,3].forEach(function(i){var xy=pt(i,24);out+="<line x1=\""+cx+"\" y1=\""+cy+"\" x2=\""+xy[0]+"\" y2=\""+xy[1]+"\" stroke=\"#dce9df\"/>"});out+="<polygon points=\""+scores.map(function(s,i){return pt(i,s).join(",")}).join(" ")+"\" fill=\"#8bb8a0\" fill-opacity=\".38\" stroke=\"#447b5f\" stroke-width=\"2.5\"/>";scores.forEach(function(s,i){var xy=pt(i,s);out+="<circle cx=\""+xy[0]+"\" cy=\""+xy[1]+"\" r=\"5\" fill=\"#417960\" stroke=\"white\" stroke-width=\"2\"/>"});[{x:200,y:23,a:"middle"},{x:365,y:166,a:"middle"},{x:200,y:323,a:"middle"},{x:35,y:166,a:"middle"}].forEach(function(o,i){out+="<text x=\""+o.x+"\" y=\""+o.y+"\" text-anchor=\""+o.a+"\" font-size=\"14\" font-weight=\"650\" fill=\"#456452\">"+dims[i].title+"</text><text x=\""+o.x+"\" y=\""+(o.y+17)+"\" text-anchor=\""+o.a+"\" font-size=\"11\" fill=\"#869c8a\">"+scores[i]+" / 24</text>"});el("radar").innerHTML=out}
function renderResult(){if(ans.some(function(x){return x===null})){idx=ans.findIndex(function(x){return x===null});renderQuiz(true);return}show("result");var s=stats();el("totalScore").textContent=s.total;el("totalCopy").textContent="总分 "+s.total+" 分。它是四个体验维度的简单相加，不设未经验证的总体严重程度阈值。";radar(s.scores);el("dimensionResults").innerHTML=s.scores.map(function(score,i){var d=dims[i];return "<article class=\"dim-card\"><div class=\"dim-head\"><div class=\"dim-title\">"+d.title+"</div><div class=\"dim-score\">"+score+" <small>/ 24</small></div></div><div class=\"mini-track\"><div class=\"mini-fill\" style=\"width:"+(score/24*100)+"%;--tone:"+d.color+"\"></div></div><div class=\"dim-meta\"><span>"+d.brief+"</span><span>"+level(score)+"*</span></div></article>"}).join("");var names=s.leaders.map(function(i){return dims[i].title+"（"+dims[i].type+"）"});var lead=s.leaders.length>1?"并列最高的体验方向："+names.join("、"):"相对突出的体验方向："+names[0];var ordered=s.scores.map(function(score,i){return{score:score,i:i}}).sort(function(a,b){return b.score-a.score||a.i-b.i});var advice=s.leaders.length===1?dims[s.leaders[0]].suggest:"本次有多个并列维度。可以先选一个自己最想了解、最不让你感到负担的方向，慢慢观察。";var comp=s.complex?"按草案规则，有至少两个维度达到 15 分，属于“复合关注”模式。得分排序只是本次观察顺序，不等于临床干预优先级。":"按草案规则，本次未达到“两个及以上维度均不少于 15 分”的复合关注条件。";el("insight").innerHTML="<span class=\"tag\">探索性分析 · 非病理诊断</span><h3>"+lead+"</h3><p>"+comp+"</p><p><strong>可以尝试：</strong>"+advice+"</p><p style=\"color:#829086;font-size:12px\">四维度从高到低："+ordered.map(function(x){return dims[x.i].title+" "+x.score+"分"}).join(" · ")+"。* 维度分段沿用所提供草案，尚未建立临床解释效度。</p>"}
function closeModal(id){el(id).classList.add("hidden");document.body.classList.remove("no-scroll")}
function openModal(id){el(id).classList.remove("hidden");document.body.classList.add("no-scroll")}
function reset(){clearTimeout(timer);try{sessionStorage.removeItem(KEY)}catch(e){}ans=Array(24).fill(null);idx=0;agreed=false;el("agree").checked=false;el("startBtn").disabled=true;el("startBtn").innerHTML="开始探索 <span aria-hidden=\"true\">↗</span>";el("resumeNote").hidden=true;closeModal("privacyModal");closeModal("shareModal");show("cover")}
function report(){var s=stats(),c=document.createElement("canvas"),W=1080,H=1660;c.width=W*2;c.height=H*2;var g=c.getContext("2d");g.scale(2,2);g.fillStyle="#f5f8f3";g.fillRect(0,0,W,H);var grad=g.createLinearGradient(0,0,W,H);grad.addColorStop(0,"#e1eee2");grad.addColorStop(1,"#faf1e8");g.fillStyle=grad;g.fillRect(0,0,W,550);function rr(x,y,w,h,r,color){g.fillStyle=color;g.beginPath();g.roundRect(x,y,w,h,r);g.fill()}function txt(t,x,y,size,color,weight,align){g.fillStyle=color;g.textAlign=align||"left";g.font=(weight||"500")+" "+size+"px -apple-system, BlinkMacSystemFont, PingFang SC, Microsoft YaHei, sans-serif";g.fillText(t,x,y)}rr(54,58,972,1544,38,"#fff");txt("SEFS   /   SUBJECTIVE EXPERIENCE",110,140,24,"#71917c","700");txt("你的主观体验地图",110,238,63,"#294c3a","650");txt("一次自我观察，而不是对你的定义。",110,300,29,"#758c7a");rr(110,345,860,236,28,"#edf5ec");txt(String(s.total),145,500,124,"#2e6147","700");txt("/ 96",355,491,38,"#829987");txt("四个维度总分 · 不对应临床诊断阈值",145,546,24,"#63836b");txt("四个体验维度",110,653,38,"#294b39","700");s.scores.forEach(function(score,i){var y=722+i*153,d=dims[i];txt(d.title,110,y,31,"#355342","600");txt(String(score)+" / 24",970,y,30,"#355342","600","right");rr(110,y+31,860,20,10,"#e9efea");if(score>0)rr(110,y+31,Math.max(16,score/24*860),20,10,d.color);txt(level(score)+"（草案分段）",110,y+94,23,"#829285")});var highest=s.leaders.map(function(i){return dims[i].title}).join("、");rr(110,1345,860,124,20,"#f1f6f1");txt("突出方向："+highest,140,1401,27,"#416a50","600");txt(s.complex?"复合关注：至少两个维度达到 15 分":"本次未达到复合关注规则",140,1445,24,"#6a8773");txt("本报告为探索性自评；量表阈值及类型尚未经验证。",110,1534,22,"#859488");txt("仅供个人参考，不可用于诊断或决定治疗。",110,1574,22,"#859488");var url=c.toDataURL("image/png");el("reportImage").src=url;el("downloadLink").href=url;openModal("shareModal")}
el("agree").addEventListener("change",function(e){agreed=e.target.checked;el("startBtn").disabled=!agreed;store()});el("startBtn").addEventListener("click",function(){if(!agreed)return;renderQuiz(true)});el("options").addEventListener("click",function(e){var b=e.target.closest("button[data-score]");if(b)choose(Number(b.getAttribute("data-score")))});el("backBtn").addEventListener("click",function(){clearTimeout(timer);if(idx>0){idx--;renderQuiz(true)}});el("nextBtn").addEventListener("click",advance);el("exitBtn").addEventListener("click",function(){clearTimeout(timer);show("cover");el("resumeNote").hidden=filled()===0;el("startBtn").innerHTML=filled()>0?"继续上次探索 <span aria-hidden=\"true\">↗</span>":"开始探索 <span aria-hidden=\"true\">↗</span>"});el("privacyBtn").addEventListener("click",function(){openModal("privacyModal")});el("shareBtn").addEventListener("click",report);el("restartBtn").addEventListener("click",function(){if(confirm("重新测评会清除本次答案和报告。确定重新开始吗？"))reset()});el("clearBtn").addEventListener("click",function(){if(confirm("确定清除本次所有答案吗？"))reset()});document.querySelectorAll("[data-close]").forEach(function(b){b.addEventListener("click",function(){closeModal(b.getAttribute("data-close"))})});["privacyModal","shareModal"].forEach(function(id){el(id).addEventListener("click",function(e){if(e.target===el(id))closeModal(id)})});document.addEventListener("keydown",function(e){if(e.key==="Escape"){closeModal("privacyModal");closeModal("shareModal")}});
load();el("agree").checked=agreed;el("startBtn").disabled=!agreed;if(view==="quiz")renderQuiz(false);else if(view==="result")renderResult();else{el("resumeNote").hidden=filled()===0;if(filled()>0)el("startBtn").innerHTML="继续上次探索 <span aria-hidden=\"true\">↗</span>"}
})();